---
- hosts: all
  gather_facts: false
  become: true
  roles:
  - rsyslog
  post_tasks:
  - name: Ver que onda
    shell: " systemctl status rsyslog | grep -i 'active' | awk '{print $2}' "
    register: salida

  - name: Debugear
    debug:
      msg: "El {{ svc }} del {{ inventory_hostname }} se encuentra {{ salida.stdout | quote }}"  